### ISSUE TITLE
Add Deals to home page

### ISSUE THREAD

**Issue by Jragon** [york-rwsa/a5-flights#11]
Sup homies,

Have a look at this for a potential design. I'll go forward with it if you like it.

If you guys could come up with some text and images to go on the cards that'd be great :heart:

![image](https://user-images.githubusercontent.com/845112/48347137-48b23200-e675-11e8-9a71-8a5ec14ab895.png)

**Comment by aj1134** [comment]
Brilliant! Amazing Design! Just how I pictured it! :)

**Comment by admccart** [comment]
£600 pp for a week in Majorca

https://goo.gl/images/f6JVEZ

**Comment by Jragon** [comment]
![image](https://user-images.githubusercontent.com/845112/48416406-09084a80-e748-11e8-8c12-c2fa6afd6277.png)

B E A U T I F U L

**Comment by Jragon** [comment]
![image](https://user-images.githubusercontent.com/845112/48416455-29380980-e748-11e8-919a-2af85612e5bc.png)

U N U S A B L E

**Comment by aj1134** [comment]
Oh No! 😿 -  I'm sure this is solvable though! 🎖 

> "Success is not final, failure is not fatal: it is the courage to continue that counts"
(Winston Churchill)

**Comment by Jragon** [comment]
![image](https://user-images.githubusercontent.com/845112/48416786-00644400-e749-11e8-86aa-db757bf77575.png)

U S A B L E

**Comment by aj1134** [comment]
WELL DONE! 👏 

> "Wars may be fought with weapons, but they are won by men. It is the spirit of men who follow and of the man who leads that gains the victory."
(George S. Patton)

**Comment by jk1186** [comment]
There is a typo on the 4th deal where it says Majorca in the title but in the description and image it shows Thailand.
<img width="259" alt="image" src="https://user-images.githubusercontent.com/44897802/48417819-a3b65880-e74b-11e8-9476-a64ae8055f6d.png">

**Comment by Jragon** [comment]
Don't know what you're talking about...

![image](https://user-images.githubusercontent.com/845112/48418068-440c7d00-e74c-11e8-9633-23bf38fcc103.png)

**Comment by jk1186** [comment]
Well done. that was quick.💨💨💨
