### ISSUE TITLE
Car Rental - Template

### ISSUE THREAD

**Issue by jk1186** [york-rwsa/a5-flights#17]
<img width="414" alt="image" src="https://user-images.githubusercontent.com/44897802/48615686-7b1ba200-e989-11e8-970f-9b4c733a5a4f.png">
<img width="414" alt="image" src="https://user-images.githubusercontent.com/44897802/48615784-bf0ea700-e989-11e8-98b7-f9b402b059b5.png">

**Comment by aj1134** [comment]
Wow this looks so good! 

Based on our personas, I could already find some relevant information that we can add:

how many seats are in the car (how many people will fit). 
If it is automatic or manual.
What colour the car is.
 what side you drive on in the country.
 How public transport is in the area (it;s quality).

I think personally that it would also be good to add an image to show how the car looks - some people like looking at images before information :)

Thanks,

Alfie. x

**Comment by jk1186** [comment]
<img width="794" alt="image" src="https://user-images.githubusercontent.com/44897802/48616896-d26f4180-e98c-11e8-9196-1901a6115229.png">
Couple pf ypur suggestions have been added.

**Comment by aj1134** [comment]
Dear A5 Flights Team,

Here are some pictures that you can use:

![image](https://user-images.githubusercontent.com/44804358/48617309-00a15100-e98e-11e8-9e7c-14140b535202.png) - Vauxhall Zafira Tourer

![image](https://user-images.githubusercontent.com/44804358/48617348-2169a680-e98e-11e8-95ad-1372b319cb9c.png) - Toyota Aygo

![image](https://user-images.githubusercontent.com/44804358/48617410-4fe78180-e98e-11e8-988a-7143def43781.png) - Vauxhall Corsa

![image](https://user-images.githubusercontent.com/44804358/48617491-80c7b680-e98e-11e8-8a60-919ad8ca00e9.png) - Vauxhall Insignia

![image](https://user-images.githubusercontent.com/44804358/48617549-afde2800-e98e-11e8-83f8-4eed5bd92b98.png) - Range Rover

![image](https://user-images.githubusercontent.com/44804358/48617586-c1273480-e98e-11e8-9d50-24d9a9a46d1d.png) - Jaguar

![image](https://user-images.githubusercontent.com/44804358/48617626-e156f380-e98e-11e8-9010-eea421d5fc98.png) - Mercedes Sprinter

Thanks,

Alfie 👍 

A5 flights team goals 😉  : 

> "Happiness is when what you think, what you say, and what you do are in harmony."
(Mohandas Karamchand Gandhi)

**Comment by Jragon** [comment]
Okay we're pretty much there. Could do with some feed back. I think we need the auto complete like with the airports.

![chrome_2018-11-16_18-08-49](https://user-images.githubusercontent.com/845112/48639229-e043b780-e9ca-11e8-929b-d9f4790449bf.png)
![chrome_2018-11-16_18-08-55](https://user-images.githubusercontent.com/845112/48639231-e2a61180-e9ca-11e8-9604-c8e5b2c38378.png)
![chrome_2018-11-16_18-09-24](https://user-images.githubusercontent.com/845112/48639237-e46fd500-e9ca-11e8-802e-ab707dc8189a.png)

**Comment by Jragon** [comment]
Also need to add transmission type to the filters

**Comment by aj1134** [comment]
![image](https://user-images.githubusercontent.com/44804358/48704061-87079e00-ebed-11e8-95f7-3ad49576433c.png)

**Comment by Jragon** [comment]
Great feedback guys ❤️ 

![image](https://user-images.githubusercontent.com/845112/48710218-942d8880-ebff-11e8-9f3f-e959beb3423e.png)

How's this?
