### ISSUE TITLE
A section for reviews!

### ISSUE THREAD

**Issue by aj1134** [york-rwsa/a5-flights#19]
Dear A5 Flights team,

Since our personas, it has become obvious that users want a review section - especially a section that identifies trusted reviewers (so they know that they can trust what the person/reviewer is saying).

Thanks,

Alfie. 👍

**Comment by Jragon** [comment]
Reviewing what? Please add a possible design markup. Take a screenshot and write what you think could be different. 

Reviewing airlines? Car types? Specific flights (impossible)?

**Comment by Jragon** [comment]
![image](https://user-images.githubusercontent.com/845112/48710998-f2f40180-ec01-11e8-9799-5ea439c2ebff.png)

How's this?

**Comment by aj1134** [comment]
![image](https://user-images.githubusercontent.com/44804358/48770098-48d5b180-ecb5-11e8-8853-82adf32ad316.png)
 
Looking good Rory,

maybe the review section can pop when the bit that say "300 reviews" for example is clicked (hyperlink) - we can just make up some randomly generated reviews for the prototype.

Thanks,

Alfie.

**Comment by Jragon** [comment]
![chrome_dwgsrevubb](https://user-images.githubusercontent.com/845112/48844515-f6b68e00-ed91-11e8-8c93-bc5e62c76103.png)

How's this?

**Comment by aj1134** [comment]
Rory,

That looks great mate, well done and keep up the good work!

Thanks and see you tomorrow,

Alfie! 👍
