### ISSUE TITLE
Add details modal to search page

### ISSUE THREAD

**Issue by aj1134** [york-rwsa/a5-flights#2]
Add this as per the balsamiq mockup:
![image](https://user-images.githubusercontent.com/44804358/48061259-4011b580-e1b6-11e8-8d40-33845064750f.png)

It would be worth changing the 'Book Now!' button to say 'Details' as one of Norman's law.

**Comment by Jragon** [comment]
As you can see the workflow is now working:

![2018-11-06_13-30-53](https://user-images.githubusercontent.com/845112/48067459-46a92880-e1c8-11e8-904a-c0d0e065a70f.gif)


Here is what it looks like when there is no return:
![chrome_2018-11-06_13-32-45](https://user-images.githubusercontent.com/845112/48067547-75270380-e1c8-11e8-9205-c34adda63730.png)


Please let me know what you think, if it's good enough then feel free to close the issue :smile:

(this is available on the link in the readme section, try it out for yourself)
