### ISSUE TITLE
Add auto complete to car location

### ISSUE THREAD

**Issue by Jragon** [york-rwsa/a5-flights#20]
As mentioned in #17. Autocomplete would help the user greatly since they'll always be picking up from an airport

**Comment by Jragon** [comment]
![image](https://user-images.githubusercontent.com/845112/48723729-53456c00-ec1f-11e8-94bf-e8c8a4acf142.png)

as usual my work is flawless - if you could comment saying how great it is that'd be lovely.

**Comment by admccart** [comment]
flawless wow
