### ISSUE TITLE
Filters on mobile - slider size

### ISSUE THREAD

**Issue by aj1134** [york-rwsa/a5-flights#4]
![image](https://user-images.githubusercontent.com/44804358/48236802-c1866500-e3bb-11e8-8704-a1108245abc4.png)

(Screenshot taken 01:08 on 09/11/2018)

It may be useful if the sliders had a bigger set of circles for the user to interact with - as some users who like to interact with things quickly and are maybe faster than other users at typing and interacting with mobile phones may be get frustrated that the size of the circles/dots on the sliders are not big enough to suit their needs.

thanks,

Alfie.

**Comment by Jragon** [comment]
![img_2365](https://user-images.githubusercontent.com/845112/48261372-c75d6400-e416-11e8-9e33-861c94afec09.png)

Slider size has been increased :fire:

**Comment by jk1186** [comment]
Looks great! You're so great Rory :fire: :fire: we can close this issue out now

**Comment by Jragon** [comment]
Glad you think so :heart: :heart:
