### ISSUE TITLE
Don  Norman's Principles

### ISSUE THREAD

**Issue by aj1134** [york-rwsa/a5-flights#5]
Visibility and Affordance on the page where you search for flights:
![image](https://user-images.githubusercontent.com/44804358/48237143-4b82fd80-e3bd-11e8-9153-dc433e1952c9.png)

It may be a good idea to add a button that clearly represents going back to the home page - as it may not be clear that pressing "A5 Flights" at the top takes you back to the home page on a desktop browser. I think it may be a good idea to put the home button in the top left hand corner (where highlighted) and for it to look something like this:

![image](https://user-images.githubusercontent.com/44804358/48237634-6c4c5280-e3bf-11e8-8aa8-8e36f76b385b.png)

(Photo taken from https://www.flaticon.com/premium-icon/home-button_61972 and was accessed at 01:32am on 09/11/2018)

As this shows that Don Norman's laws of visibility and affordance are being followed.

Additionally, to possibly gain some extra marks through consistency - it may be a good idea to make the drop down arrows for these drop down lists to look the same:

![image](https://user-images.githubusercontent.com/44804358/48237874-a2d69d00-e3c0-11e8-88d3-ba66e263544d.png)

![image](https://user-images.githubusercontent.com/44804358/48237910-c00b6b80-e3c0-11e8-9136-34fac3127fe2.png)

thanks,

Alfie.

**Comment by Jragon** [comment]
![img_2366](https://user-images.githubusercontent.com/845112/48261346-a72da500-e416-11e8-8777-96fbfa6a26ec.png)

I've added a home icon. Let me know what you think

**Comment by aj1134** [comment]
Oh very good work, this looks like it can be closed now - can't wait to see what potential users think of this in our upcoming scenario - based research! 👍
