### ISSUE TITLE
General ToDos

### ISSUE THREAD

**Issue by Jragon** [york-rwsa/a5-flights#6]
From the whatsapp group:

- [ ] Conduct new interviews (question script 2) - (everyone)
- [ ] Construct new persona and scenario - (Alfie/Dan)
- [ ] Finish first section of report and logbook up to do date (Jack and Adam)
- [ ] Have a look at issues and add feedback ready to close issues (EVERYONE)
- [ ] Prototype (Rory)

**Comment by admccart** [comment]
10/10 v 🔥
