### ISSUE TITLE
Review how our prototype matches the persona created based on interviews.

### ISSUE THREAD

**Issue by aj1134** [york-rwsa/a5-flights#9]
Hi A5 Flights Team!

Hope you are all having a good end to your weekend. :)

Here is a persona based on our first set of interviews that I have created - https://docs.google.com/document/d/1KASNYq-qrgobkFgtZiXRwSzEu3R8PwU57jumdt9SMRQ/edit?usp=sharing

Overview of his Key Goals:
To be able to book his 3 journeys in 2019 on a new, trusted flight comparison website which has the following features:
A section for honest reviews - where there is some sort of system to tell if a reviewer is well - trusted by others.
A way to filter and sort his searches to be able to search for the cheapest flight from specific airlines that he trusts (such as TUI, Virgin,  CathayPacific and America).
A way to see information about car rentals and public transport - as that will affect his decision in choosing a car rental or not.
Have a system which is available on both a desktop/laptop and mobile phone, so he can choose a flight on his computer and then view details later about it on his phone - as a phone is more portable, so is used more regularly.
A website that is easy to navigate on both mobile phone and his desktop at home.
A system that will allow him to book flights and hotels separately as well as together - as booking them seperately is usually cheaper.
A system that somehow tell him roughly how much money he can save travelling to a non - local airport in some cases, including how many hours it will take to travel and how much money will be saved - as this affects his choice.

To have fun on his 3 planned journeys/trips.

I think in tomorrows meeting we should have a discussion about how we can use this persona and the scenario that Daniel is creating to better our prototype. 👍 

thanks,

Alfie.

**Comment by Jragon** [comment]
refer to #22 and #23
